version: '3.3'
services:
  nginx:
    image: nginx:alpine
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    container_name: nginx
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: "0"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./promtail/promtail.yaml:/etc/promtail/config.yaml
      - ./nginx/logs:/var/log/nginx
    command:
      - '-config.file=/etc/promtail/config.yaml'
      - '-config.expand-env=true'
    depends_on:
      - loki
