version: "3.3"

volumes:
    prometheus_data: {}

services:

#### NODE-EXPORTER ####

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.udev.data=/rootfs/run/udev/data'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    ports:
      - "9100:9100"

##### PROMETHEUS #####

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"

##### GRAFANA ######

  grafana:
    image: grafana/grafana-enterprise
    user: "0"
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    links:
      - prometheus

####### NGINX ########

  nginx:
    image: nginx:alpine
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    container_name: nginx
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"

#### APACHE ####

  httpd:
    image: httpd:latest
    container_name: apache
    volumes:
      - ./apache/logs:/var/log/httpd
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - "8081:80"

##### LOKI ######

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

#### PROMTAIL ####

  promtail:
    image: grafana/promtail:latest
    user: "0"
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail/promtail.yaml:/etc/promtail/config.yaml
      - ./nginx/logs:/var/log/nginx
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command:
      - '-config.file=/etc/promtail/config.yaml'
      - '-config.expand-env=true'
    depends_on:
      - loki
