#SPDX-License-Identifier: MIT-0
---
# tasks file for docker_install

- name: Load Os-srecific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-AmazonLinux.yml
  when: ansible_distribution == 'Amazon' 
