---
- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Create CLI plugins directory
  file:
    path: /usr/libexec/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Download Docker Compose plugin
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/libexec/docker/cli-plugins/docker-compose
    mode: '0755'

- name: Ensure Docker Compose v2 is available
  command: docker compose version
  register: compose_version
  changed_when: false

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started
