global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  repeat_interval: 10m
  receiver: 'slack-notifications'
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s
  routes:
    - receiver: telegram
      repeat_interval: 1m
      matchers: ["alertname=hardware_cpu"]
    - receiver: 'slack-notifications'
      repeat_interval: 1m
      matchers: ["alertname=hardware_memory"]


receivers:
  - name: telegram
    telegram_configs:
    - api_url: 'https://api.telegram.org'
      bot_token: '7016934395:AAF-FDNil5DyM2rDIRwijXwgDX7fMsGpKBE'
      chat_id: 560373525
#      parse_mode: 'Markdown'
      message: "ALERT: {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}"
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#monitoring'
      send_resolved: false
