version: '3.3'

volumes:
    prometheus_data: {}

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.udev.data=/rootfs/run/udev/data'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-enterprise
    user: "0"
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - "./grafana:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    links:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    user: "0"
    container_name: alertmanager
    volumes:
      - ./alermanager:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alermanager'
      - '--web.listen-address=0.0.0.0:9093'
    restart: unless-stopped
    ports:
      - "9093:9093"
