route:
  repeat_interval: 10m
  receiver: telegram
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: telegram
    telegram_configs:
    - api_url: 'https://api.telegram.org'
      bot_token: 'xxx'
      chat_id: 1111
#      parse_mode: 'Markdown'
      message: "ALERT: {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}"
