FROM nginx:alpine
EXPOSE 80 443

COPY nginx.conf /etc/nginx/nginx.conf
COPY ./etc/nginx/conf.d/my_conf.conf /etc/nginx/conf.d

COPY ./letsencrypt /etc/letsencrypt
COPY ./www /var/www
COPY ports.conf /etc/apache2/conf.d/


RUN  apk add nginx-mod-http-image-filter apache2 && \
	 sed '/Listen 80/d' /etc/apache2/httpd.conf && \
	 httpd

