apiVersion: 1

deleteDatasouces:
  - name: loki

datasources:
- name: loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090

